version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app


  app_user:
    build:
      context: .
      dockerfile: /app_user/Dockerfile
    ports:
      - "88:88"
    depends_on:
      - postgres
    networks:
      - app

  app_post:
    build:
      context: .
      dockerfile: /app_post/Dockerfile
    ports:
      - "87:87"
    depends_on:
      - postgres
    networks:
      - app

  app_notification:
    build:
      context: .
      dockerfile: /app_notification/Dockerfile
    ports:
      - "86:86"
    depends_on:
      - postgres
    networks:
      - app

  app_musician:
    build:
      context: .
      dockerfile: /app_musician/Dockerfile
    ports:
      - "85:85"
    depends_on:
      - postgres
    networks:
      - app

  app_message:
    build:
      context: .
      dockerfile: /app_message/Dockerfile
    ports:
      - "84:84"
    depends_on:
      - postgres
    networks:
      - app
      -
  app_location:
    build:
      context: .
      dockerfile: /app_location/Dockerfile
    ports:
      - "83:83"
    depends_on:
      - postgres
    networks:
      - app

  app_comment:
    build:
      context: .
      dockerfile: /app_comment/Dockerfile
    ports:
      - "82:82"
    depends_on:
      - postgres
    networks:
      - app

  app_chat:
    build:
      context: .
      dockerfile: /app_chat/Dockerfile
    ports:
      - "81:81"
    depends_on:
      - postgres
    networks:
      - app

  app_band:
    build:
      context: .
      dockerfile: /app_band/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - app

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pas@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    restart: always
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=1234
    networks:
      - minio_net


networks:
  minio_net:
  app:
volumes:
  postgres_data: