version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app


#  rabbitmq:
#    image: "rabbitmq:management"
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    networks:
#      - app

  app_user:
    build:
      context: ./
      dockerfile: ./app_user/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres-delivery
    networks:
      - app

#  gateway:
#    build:
#      context: ./
#      dockerfile: ./gateway/Dockerfile
#    ports:
#      - "8000:8000"
#    # depends_on:
#    # - postgres-cart
#    # - rabbitmq
#    labels:
#      logging: "promtail"
#      logging_jobname: "containerlogs"
#    networks:
#      - app

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: vkryazhevskikh@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - app
###########################
  ############################
  ##############################
#  keycloak:
#    image: quay.io/keycloak/keycloak:23.0.1
#    volumes:
#      - ./realm-export.json:/opt/jboss/keycloak/imports/realm-export.json
#    ports:
#      - "8080:8080"
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#    command:
#      - "start-dev"
#      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
#      - "-Dkeycloak.migration.action=import"
#      - "-Dkeycloak.migration.provider=singleFile"
#      - "-Dkeycloak.migration.file=/opt/jboss/keycloak/imports/realm-export.json"
#    networks:
#      - app

networks:
  app:
#    name: app

volumes:
  postgres_data: