"""Added user table

Revision ID: 7343193402e7
Revises: 
Create Date: 2024-01-16 16:43:22.887366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7343193402e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('members', sa.JSON(), nullable=False),
    sa.Column('genre', sa.Enum('METAL', 'METALCORE', 'ROCK', 'ELSE', name='genretypes'), nullable=False),
    sa.Column('photo', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bands_id'), 'bands', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bands_id'), table_name='bands')
    op.drop_table('bands')
    # ### end Alembic commands ###
