"""Added user table

Revision ID: 8339d02fdb15
Revises: 
Create Date: 2024-01-16 16:45:26.190530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8339d02fdb15'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('musicians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('genre', sa.Enum('METAL', 'METALCORE', 'ROCK', 'ELSE', name='genretypes'), nullable=False),
    sa.Column('instrument', sa.Enum('METAL', 'METALCORE', 'ROCK', 'ELSE', name='instrumenttypes'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_musicians_id'), 'musicians', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_musicians_id'), table_name='musicians')
    op.drop_table('musicians')
    # ### end Alembic commands ###
