"""Added user table

Revision ID: 8ba631edad97
Revises: 
Create Date: 2024-01-16 16:41:42.574574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ba631edad97'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('caption', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('likes', sa.JSON(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('comments', sa.JSON(), nullable=False),
    sa.Column('attachment', sa.JSON(), nullable=False),
    sa.Column('creator_type', sa.Enum('USER', 'BAND', 'LOCATION', name='creatortypes'), nullable=False),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_posts_post_id'), 'posts', ['post_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_post_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
